name: Run Selenium Tests

on:
  workflow_dispatch:    # Manual trigger
  schedule:
    - cron: '0 0 * * *'  # Nightly trigger at midnight UTC (change as needed)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.5'  # Specify your Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Install Chrome browser
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      
      # Step 4: Install browser drivers (e.g., Chrome, Firefox)
      - name: Set up WebDriver
        run: |
          wget https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      # Step 5: Run the Selenium tests
      - name: Run Selenium Tests on ${{ matrix.browser }}
        run: |
          pytest