name: Run Selenium Tests

on:
  workflow_dispatch:    # Manual trigger
  schedule:
    - cron: '0 0 * * *'  # Nightly trigger at midnight UTC (change as needed)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify your Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Step 4: Install Chrome
      - name: Install chrome  
        uses: browser-actions/setup-chrome@v1
      
      # Step 5: Run the Selenium tests
      - name: Run Selenium Tests 
        run: |
          mkdir -p reports   
          pytest -vs --html=reports/reports.html
          chmod 777  /home/runner/work/TakeHomeExercise/TakeHomeExercise/reports/
      
      # Step 6: Make report available in artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: /home/runner/work/TakeHomeExercise/TakeHomeExercise/reports/*